Tracer: Adding lock to make it threadsafe
stack-of-tasks/dynamic-graph pull request #79
Opened 2020-09-23 12:34 UTC by jviereck

With the existing code we ran into a threading problem. It sometimes happened that the Tracer was stopped and the files closed while still the record() function tried to write to the files. This can happen when using multiple threads (like one thread for the main control and another for python).

The following patch makes sure the `play` variable is locked. This ensures during the `Tracer::record()` call, that the files cannot be closed when using the sequence `tracer.stop(); tracer.close()` from python.

2020-09-23 12:57 UTC, jmirabel commented on src/traces/tracer.cpp
> +  play_mtx.lock();
Use a scoped lock so that the mutex is released even if the function throws.

2020-09-23 13:06 UTC, jmirabel requested changes
I think your changes do not solve the race condition problem. it only solves it for the sequence you say.

I would go for a cleaner solution. The race condition is due to the fact that both `Tracer::record` and `Tracer::closeFiles` can be called at the same time so put the lock in these functions. While doing so, you should pay attention to:
- make sure that `record` never hangs and
- ensure that throwing an exception won't leave the mutex locked (the primary intent of scoped lock).

2020-09-23 14:01 UTC, jviereck commented
@jmirabel thanks for your feedback. I reworked the PR and did a force push.

2020-09-23 14:28 UTC, jmirabel approved these changes
This is exactly what I had in mind. Thanks.

2020-09-23 16:54 UTC, jviereck commented
The 16.04 build is failing as this change requires C++11 (for `std::mutex` etc). Is this a problem?

2020-09-23 16:56 UTC, olivier-stasse commented
> The 16.04 build is failing as this change requires C++11 (for `std::mutex` etc). Is this a problem?

The main reason we kept 16.04 is because some of our robots were in 16.04. As it is not anymore the case, we will drop very very soon support for 16.04 LTS unless one of the user is asking for it.

2020-09-23 16:57 UTC, nim65s commented
This will be automatically fixed in #78 :
https://github.com/stack-of-tasks/dynamic-graph/blob/99e47c7c75dd93637dd4f463251a81335297f741/CMakeLists.txt#L29

2020-11-09 09:21 UTC, jviereck commented
Hi folks, is there something from keeping this to get merged?

2020-11-09 09:41 UTC, jmirabel commented
From my side, nothing.

2020-11-09 10:08 UTC, olivier-stasse commented
I will let @nim65s decide if it can be merged or not in the next release.
Otherwise I will merge it just after the release.
Thanks for the contribution.

2020-11-09 11:43 UTC, nim65s commented
Hi @jviereck,

I've been very late on the maintenance of the SoT lately, but I can allocate some time for it again. I'll be able to test and merge this soon

2020-11-12 17:25 UTC, nim65s commented
I ran integrations tests with that, and it works :)
CI is failing because of C++ standard, which was updated in master/devel anyway, so I'll merge this and this should make CI happy.

2020-11-12 17:25 UTC, merged